spring:
  application:
    name: health-log
  docker:
    compose:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/healthlog
    username: healthlog
    password: healthlog
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  # using flyway
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
